"""Initial

Revision ID: bc1497cdf1b5
Revises: 
Create Date: 2025-07-23 22:34:37.674387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1497cdf1b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emeaik_pl_api_key',
    sa.Column('eaik_id', sa.Integer(), nullable=False),
    sa.Column('eaik_username', sa.String(), nullable=True),
    sa.Column('eaik_key', sa.String(), server_default=sa.text('gen_random_uuid()::text'), nullable=True),
    sa.Column('eaik_is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.PrimaryKeyConstraint('eaik_id'),
    schema='azure_ai'
    )
    op.create_table('emeaik_pl_chat',
    sa.Column('eapc_id', sa.Integer(), nullable=False),
    sa.Column('eapc_conv_uuid', sa.String(), nullable=True),
    sa.Column('eapc_order', sa.Integer(), nullable=True),
    sa.Column('eapc_role', sa.String(), nullable=True),
    sa.Column('eapc_text', sa.Text(), nullable=True),
    sa.Column('eapc_username', sa.String(), nullable=True),
    sa.Column('eapc_model', sa.String(), nullable=True),
    sa.Column('eaik_id', sa.Integer(), nullable=True),
    sa.Column('usrinsert', sa.String(), nullable=True),
    sa.Column('dteinsert', sa.DateTime(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('eapc_id'),
    schema='azure_ai'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emeaik_pl_chat', schema='azure_ai')
    op.drop_table('emeaik_pl_api_key', schema='azure_ai')
    # ### end Alembic commands ###
